name: Apply GitHub changes
on:
  push:
    branches: [main]
    paths:
      - "repos/**"
      - "files/**"
jobs:
  apply:
    runs-on: ubuntu-latest
    environment:
      name: github
      deployment: true
    steps:
      - uses: actions/checkout@v6
      - run: |
          gh extension install babarot/gh-infra
          gh infra apply ./repos/ --auto-approve
        env:
          GH_TOKEN: ${{ secrets.GH_APP_CLIENT_TOKEN }}
